name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees: ["mobilegmYT"]
body:
  - type: markdown
    attributes:
      value: |
        MCPI++ not launching? Missing items? Report those bugs here:
  - type: checkboxes
    attributes:
      label: Confirmations
      options:
      - label: I searched for similar bug reports in https://github.com/mobilegmYT/mcpi-reborn-extended/issues and found none were relevant.
        required: true
      - label: I tried using the latest MCPI++ version from APT or the Releases tab.
        required: true
  - type: input
    id: desc
    attributes:
      label: What happened?
      description: Briefly explain what happened.
      placeholder: "Ex. MCPI++ not launching, MCPI++ has broken features"
    validations:
      required: true
  - type: textarea
    id: desc-long
    attributes:
      label: Description
      description: A clear and concise description of what the bug is and any personal attempts you made to fix it. Feel free to link to screenshots if it is a visual issue.
      placeholder: Tell us more!
    validations: 
      required: true
  - type: input
    id: os
    attributes:
      label: What is your operating system and CPU arch?
      description: Let us know what is your OS to better solve your problem.
      placeholder: Ex. Raspberry Pi OS armhf, Ubuntu 18.04 arm64
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: (Optional) Error log? Terminal output? Debug messages?
      description: Please provide error log or terminal output, if available.
      placeholder: Paste your terminal output/error log here
      render: bash
    validations:
      required: false
