name: Update CHANGELOG

on: [push]

jobs:
  package:
    name: Generate LATEST_CHANGELOG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 'source'
      - name: Read Version
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.2.1
        with:
          validation_level: warn
          version: ${{ env.VERSION }}
          path: ./docs/CHANGELOG.md 
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Generate LATEST_CHANGELOG
        run: |
          echo "${{ steps.changelog_reader.outputs.changes }}" > LATEST_CHANGELOG
      - name: Push Changes
        run: |
          git add -A
          git commit -m "Update LATEST_CHANGELOG for ${{ steps.tag_name.outputs.current_version }}"
          git push --force