name: Generate Release Notes

on:
  push:
    branches:
      - "**"

jobs:
  package:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          ref: 'source'
      - name: Read Version
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Read Commit Hash
        run: |
          echo "HASH=$(git show-ref -s ${{ env.VERSION }})" >> $GITHUB_ENV
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.2.1
        with:
          validation_level: warn
          version: ${{ env.VERSION }}
          path: ./docs/CHANGELOG.md 
      - name: Checkout APT Repo
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Generate LATEST_RELEASE
        run: |
          echo "${{ steps.changelog_reader.outputs.changes }}" > LATEST_RELEASE
          echo "View the source code commit for [${{ env.VERSION }}](https://github.com/NoozSBC/mcpi-reborn-extended/commit/${{ env.COMMIT }})." >> LATEST_RELEASE
      - name: Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config pull.rebase false
          
          git pull
          git add -A
          git commit -m "[AUTO] Update LATEST_RELEASE for ${{ env.VERSION }}"
          git push